# Default values for node-Version.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.

replicaCount: 1
restartPolicy: Never

image:
  repository: docker.artifactory/node-version
  tag: latest
  secretName: regsecret
  pullPolicy: Always

#Uncomment if you want to generate docker credentials using helm
#imageCredentials:
#  registry: docker.artifactory
#  username: admin
#  password: password

service:
  annotations: {}
  clusterIP: ""
  externalIPs: []
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  type: LoadBalancer
  port: 3000
  nodePort: ""

resources: {}

nodeSelector: {}